method: bc

epochs: 10000
batch_size: 128
mlp_config:
        hidden_dims:
           - 128
           - 128
           - 128
        dropout: 0
cond_force_retrain: False
model_name: "bc"
lr: 1e-4
weight-decay: 1e-6

obs_horizon: 1
act_horizon: 1

#[I 2025-02-18 10:42:00,961] Trial 46 finished with value: 37.33440075374686 and parameters: {'epochs': 863, 'batch_size': 16, 'num_layers': 3, 'layer_size_0': 128, 'layer_size_1': 256, 'layer_size_2': 128}. Best is trial 46 with value: 37.33440075374686.

