method: bc

epochs: 1000
batch_size: 128
mlp_config:
  hidden_dims:
     - 256
     - 256
     - 256
  dropout: 0.0
model_name: "bc_img"
cond_force_retrain: True
lr: 1e-4
weight_decay: 1e-6

#obs_horizon: 1
#act_horizon: 1
