method: cond
k_neighbors: 250
lookback: 1
decay_rate: 0

#{'epochs': 257, 'neighbors': 749}


epochs: 257
batch_size: 128
hidden_dims:
   - 256
   - 256
   - 256
model_name: "dan_img"
cond_force_retrain: True
dropout_rate: 0.0
