method: cond
k_neighbors: 639
lookback: 11
decay_rate: -2.3286122
ratio: 0.0777
#Best parameters:  {'k_neighbors': 639, 'lookback': 11, 'decay_rate': -2.3286122577463573, 'ratio': 0.07770605738873454}

epochs: 1000
batch_size: 64
hidden_dims:
   - 128
   - 128
   - 128
cond_force_retrain: True
dropout: 0
