method: cond
k: 10
lookback: 1
decay_rate: 0
final_neighbors_ratio: 1

epochs: 1000
batch_size: 128
mlp_config:
  hidden_dims:
     - 512
     - 512
     - 512
  dropout: 0.0
model_name: "ns_dan_img"
cond_force_retrain: True
lr: 1e-4
weight_decay: 1e-6


#obs_horizon: 0
#act_horizon: 0
