seed: 42
name: "hopper-expert-v2"
cams:
  - track
mixed: True
retrieval:
        demo_pkl: "data/hopper-expert-v2_1_kpt.pkl"
        type: 'keypoint'
state:
        demo_pkl: "data/hopper-expert-v2_1_kpt.pkl"
        type: 'keypoint'
delta_state:
        demo_pkl: "data/hopper-expert-v2_1_kpt.pkl"
        type: 'keypoint'
neighbor_lookup_pkl: "data/hopper-mix-neighbor-lookup.pkl"
mixed: True
