seed: 42
name: "maze2d-umaze-v1"
retrieval:
        demo_pkl: "data/maze2d-umaze-v1_10.pkl"
        type: 'state'
state:
        demo_pkl: "data/maze2d-umaze-v1_10.pkl"
        type: 'state'
delta_state:
        demo_pkl: "data/maze2d-umaze-v1_10.pkl"
        type: 'state'
val_cfg: "config/env/maze_val.yml"
#neighbor_lookup_pkl: "data/maze-bc-lookup.pkl"
mixed: True
