#demo_pkl: "data/pick_and_place_task_D0/200_train.pkl"
demo_pkl: "data/pick_and_place_task_D0/1000_train.pkl"
#demo_pkl: "data/pick_and_place_task_D0/1.pkl"
type: 'state'
demo_hdf5: "data/pick_and_place_task_D0/demo.hdf5"
robosuite: True
name: PickAndPlace_D0
val_cfg: "config/env/pick_and_place_task_D0_val.yml"
#neighbor_lookup_pkl: "data/neighbor-lookup.pkl"

