#demo_pkl: "data/square_task_D1/square_task_D1_100_img_90_train.pkl"
#val_pkl: "data/square_task_D1/square_task_D1_100_img_10_val.pkl"
demo_pkl: "data/square_task_D1/square_task_D1_1000_img.pkl"
demo_hdf5: "data/square_task_D1/demo.hdf5"
stack_size: 1
robosuite: True
img: True
name: Square_D1
