demo_hdf5: "data/square_task_D0/demo.hdf5"
#neighbor_lookup_pkl: "data/stack-bc-neighbor-lookup.pkl"
stack_size: 1
robosuite: True
name: Square_D0
add_proprio: True
cams:
  - agentview
  - sideview
mixed: True
val_cfg: "config/env/square_task_D0_kpt_val.yml"
retrieval:
  demo_pkl: "data/square_task_D0/square_task_D0_100_kpt_train.pkl"
  type: 'keypoint'
state:
  demo_pkl: "data/square_task_D0/square_task_D0_100_kpt_train.pkl"
  type: 'keypoint'
delta_state:
  demo_pkl: "data/square_task_D0/square_task_D0_100_kpt_train.pkl"
  type: 'keypoint'
