demo_hdf5: "data/stack_task_D0/demo.hdf5"
#neighbor_lookup_pkl: "data/stack-bc-neighbor-lookup.pkl"
stack_size: 1
robosuite: True
name: Stack_D0
add_proprio: True
cams:
  - agentview
  - sideview
val_cfg: "config/env/stack_task_D0_semantic_kpt_val.yml"
demo_pkl: "data/stack_task_D0/stack_task_D0_100_semantic_kpt_train.pkl"
type: 'semantic_keypoint'
