#demo_pkl: "data/stack_task_D0/1000_train.pkl"
demo_pkl: "data/stack_task_D0/100.pkl"
#demo_pkl: "data/stack_task_D0/100_low_dim_train.pkl"
#demo_pkl: "data/stack_task_D0/100_low_dim.pkl"
#demo_pkl: "data/stack_task_D0/100_train.pkl"
type: 'state'
demo_hdf5: "data/stack_task_D0/demo.hdf5"
robosuite: True
name: Stack_D0
#val_cfg: "config/env/stack_task_D0_val.yml"
cams:
  #- agentview
  - frontview
  - sideview
crops:
  #agentview: [[75, 75], [200, 180]]
  frontview: [[0.40625, 0.48828125], [0.625, 0.703125]]
  sideview: [[0.34375, 0.55078125], [0.53125, 0.765625]]
