demo_pkl: "data/stack_task_D0/stack_task_D0_100_img_val.pkl"
type: 'dino'
demo_hdf5: "data/stack_task_D0/demo.hdf5"
stack_size: 1
robosuite: True
name: Square_D1
add_proprio: True
cams:
  - agentview
  - sideview
  - frontview
