demo_pkl: "data/stack_task_D0/100.pkl"
#demo_pkl: "data/stack_task_D0/100_train.pkl"
type: 'state'
demo_hdf5: "data/stack_task_D0/demo.hdf5"
robosuite: True
name: Stack_D0
#val_cfg: "config/env/stack_task_D0_val.yml"
