demo_pkl: "data/stack_task_D0/100_rgb_val.pkl"
type: 'dino'
demo_hdf5: "data/stack_task_D0/demo.hdf5"
stack_size: 1
robosuite: True
name: Stack_D0
add_proprio: True
cams:
  - agentview
  - sideview
  - frontview
