demo_pkl: "data/three_piece_assembly_task_D0/100.pkl"
#demo_pkl: "data/three_piece_assembly_task_D0/100_train.pkl"
type: 'state'
demo_hdf5: "data/three_piece_assembly_task_D0/demo.hdf5"
robosuite: True
name: ThreePieceAssembly_D0
#val_cfg: "config/env/three_piece_assembly_task_D0_val.yml"
