seed: 42
metaworld: true
env: "button-press-topdown-v2"
data:
  pkl: "data/metaworld-button-press-top-down-v2_50_shortened.pkl"
policy:
  k_neighbors:
    - 214
  lookback: 
    - 62
  decay_rate:
    - 2.4
  dtw_window: 
    - 0
