seed: 42
metaworld: true
env: "button-press-topdown-v2"
data:
  pkl: "data/metaworld-button-press-top-down-v2_50_shortened.pkl"
policy:
  k_neighbors:
    - 200
  lookback: 
    - 50
  decay_rate:
    - -0.5
  dtw_window: 
    - 25
