seed: 42
metaworld: true
env: "coffee-pull-v2"
data:
  pkl: "data/metaworld-coffee-pull-v2_30_shortened.pkl"
policy:
  k_neighbors:
    - 779
  lookback: 
    - 168
  decay_rate:
    - 37
  dtw_window: 
    - 0
