seed: 42
metaworld: true
env: "coffee-push-v2"
data:
  pkl: "data/metaworld-coffee-push-v2_50_shortened.pkl"
policy:
  k_neighbors:
    - 214
  lookback: 
    - 62
  decay_rate:
    - 2.40
  dtw_window: 
    - 0
