seed: 42
metaworld: true
env: "coffee-pull-v2"
data:
  pkl: "data/metaworld-coffee-pull-v2_50_shortened_normalized.pkl"
  # pkl: "data/metaworld-coffee-pull-v2_50_shortened.pkl"
policy:
  k_neighbors:
    - 5000
  lookback: 
    - 50
  decay_rate:
    - -1
  dtw_window: 
    - 0
  ratio:
    - 0.1
