seed: 42
metaworld: true
env: "coffee-pull-v2"
data:
  pkl: "data/metaworld-coffee-pull-v2_20_shortened.pkl"
policy:
  k_neighbors:
    - 937
  lookback: 
    - 59
  decay_rate:
    - 1.40
  dtw_window: 
    - 0
