seed: 42
metaworld: true
env: "drawer-close-v2"
data:
  pkl: "data/metaworld-drawer-close-v2_50_shortened.pkl"
policy:
  k_neighbors:
    - 1
  lookback: 
    - 1
  decay_rate:
    - 0
  dtw_window: 
    - 0
