seed: 42
metaworld: false
env: "halfcheetah-expert-v2"
data:
  pkl: "data/halfcheetah-expert-v2_50.pkl"
policy:
  k_neighbors:
    - 105
  lookback: 
    - 1
  decay_rate:
    - 0
  dtw_window: 
    - 0
