seed: 42
metaworld: false
env: "halfcheetah-expert-v2"
data:
  pkl: "data/halfcheetah-expert-v2_50.pkl"
policy:
  k_neighbors:
    - 200
  lookback: 
    - 50
  decay_rate:
    - -0.5
  dtw_window: 
    - 25
