seed: 42
metaworld: false
env: "hopper-expert-v2"
data:
  pkl: "data/hopper-expert-v2_25.pkl"
policy:
  k_neighbors:
    - 15
    - 25
    - 35
  lookback:
    - 20
    - 50
    - 75
    - 100
  decay_rate:
    - -3
  dtw_window: 
    - 50
