seed: 42
metaworld: false
env: "hopper-expert-v2"
data:
  pkl: "data/hopper-expert-v2_25.pkl"
policy:
  k_neighbors:
    - 100
  lookback: 
    - 50
  decay_rate:
    - -3
  dtw_window: 
    - 0
    - 2
    - 5
    - 10
    - 15
