seed: 42
metaworld: false
env: "hopper-expert-v2"
data:
  pkl: "data/hopper-expert-v2_25.pkl"
policy:
  k_neighbors:
    - 5
    - 200
  lookback: 
    - 50
  decay_rate:
    - -0.5
  dtw_window: 
    - 25
