seed: 42
metaworld: false
env: "hopper-expert-v2"
data:
  pkl: "data/hopper-expert-v2_25.pkl"
policy:
  k_neighbors:
    - 72
  lookback: 
    - 12
  decay_rate:
    - 1.9
  dtw_window: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
