seed: 42
metaworld: false
env: "hopper-expert-v2"
data:
  pkl: "data/hopper-expert-v2_25.pkl"
policy:
  k_neighbors:
    - 250
    - 350
  lookback: 
    - 25
    - 50
    - 75
  decay_rate:
    - -3
  dtw_window: 
    - 0
    - 5
    - 10
    - 20
