seed: 1000
metaworld: false
env: "push_t"
data:
  pkl: "data/push_t_parsed.pkl"
policy:
  k_neighbors:
    - 10
  lookback: 
    - 1
  decay_rate:
    - 0
  dtw_window: 
    - 0
  ratio:
    - 1.0
  
