seed: 42
metaworld: false
env: "walker2d-expert-v2"
data:
  pkl: "data/walker2d-expert-v2_20.pkl"
policy:
  k_neighbors:
    - 89
  lookback: 
    - 29
  decay_rate:
    - -2.20
  dtw_window: 
    - 0
