seed: 42
metaworld: false
env: "walker2d-expert-v2"
data:
  pkl: "data/walker2d-expert-v2_20.pkl"
policy:
  k_neighbors:
    - 105
  lookback: 
    - 25
  decay_rate:
    - 2.3
  dtw_window: 
    - 0
